
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWord")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWord", targetNamespace = "http://ws/", className = "ws.HelloWord")
    @ResponseWrapper(localName = "HelloWordResponse", targetNamespace = "http://ws/", className = "ws.HelloWordResponse")
    @Action(input = "http://ws/HelloWebService/HelloWordRequest", output = "http://ws/HelloWebService/HelloWordResponse")
    public String helloWord(@WebParam(name = "arg0", targetNamespace = "") String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWord2")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWord2", targetNamespace = "http://ws/", className = "ws.HelloWord2")
    @ResponseWrapper(localName = "HelloWord2Response", targetNamespace = "http://ws/", className = "ws.HelloWord2Response")
    @Action(input = "http://ws/HelloWebService/HelloWord2Request", output = "http://ws/HelloWebService/HelloWord2Response")
    public String helloWord2(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
